my.lo: /vagrant/zephir_code/my/ext/my.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/my.c -o my.lo 
kernel/main.lo: /vagrant/zephir_code/my/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /vagrant/zephir_code/my/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /vagrant/zephir_code/my/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /vagrant/zephir_code/my/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /vagrant/zephir_code/my/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /vagrant/zephir_code/my/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /vagrant/zephir_code/my/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /vagrant/zephir_code/my/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /vagrant/zephir_code/my/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /vagrant/zephir_code/my/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /vagrant/zephir_code/my/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/extended/fcall.lo: /vagrant/zephir_code/my/ext/kernel/extended/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/extended/fcall.c -o kernel/extended/fcall.lo 
kernel/require.lo: /vagrant/zephir_code/my/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /vagrant/zephir_code/my/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /vagrant/zephir_code/my/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /vagrant/zephir_code/my/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /vagrant/zephir_code/my/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /vagrant/zephir_code/my/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /vagrant/zephir_code/my/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /vagrant/zephir_code/my/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /vagrant/zephir_code/my/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /vagrant/zephir_code/my/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/kernel/exit.c -o kernel/exit.lo 
my/mongo/client.lo: /vagrant/zephir_code/my/ext/my/mongo/client.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/my/mongo/client.zep.c -o my/mongo/client.lo 
my/mongo/collection.lo: /vagrant/zephir_code/my/ext/my/mongo/collection.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/my/mongo/collection.zep.c -o my/mongo/collection.lo 
my/utils/lock.lo: /vagrant/zephir_code/my/ext/my/utils/lock.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/my/utils/lock.zep.c -o my/utils/lock.lo 
my/utils/registry.lo: /vagrant/zephir_code/my/ext/my/utils/registry.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/vagrant/zephir_code/my/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /vagrant/zephir_code/my/ext/my/utils/registry.zep.c -o my/utils/registry.lo 
$(phplibdir)/my.la: ./my.la
	$(LIBTOOL) --mode=install cp ./my.la $(phplibdir)

./my.la: $(shared_objects_my) $(MY_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_my) $(MY_SHARED_LIBADD)

